<a href="https://colab.research.google.com/github/sofiamln/03MIAR---Algoritmos-de-Optimizacion/blob/main/AG2/Sof%C3%ADa_Molina_AG2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Actividad guiada 2 de Algoritmos de Optimización

Sofía Molina Arias <br>

Link: https://colab.research.google.com/drive/1QaB2Nh3GFLfWaZvW0l0EX11F0B03qMyP?usp=sharing

Github: https://github.com/sofiamln/03MIAR---Algoritmos-de-Optimizacion.git

In [1]:
import math

##Programación Dinámica. Viaje por el rio

In [2]:
#Viaje por el río 

#Inicializamos la tabla de tarifas
#Establecemos un valor muy alto en aquellos caminos que no pueden realizarse(esto es útil dado que nuestra finalidad es minimizar el precio,
# así que si ese camino no existe, tomaría un valor muy alto para no elegir esta opción)

tarifas = [
[0,5,4,3,999,999,999],  
[999,0,999,2,3,999,11],  
[999,999, 0,1,999,4,10], 
[999,999,999, 0,5,6,9],
[999,999, 999,999,0,999,4],
[999,999, 999,999,999,0,3],
[999,999,999,999,999,999,0]
]


tarifas

[[0, 5, 4, 3, 999, 999, 999],
 [999, 0, 999, 2, 3, 999, 11],
 [999, 999, 0, 1, 999, 4, 10],
 [999, 999, 999, 0, 5, 6, 9],
 [999, 999, 999, 999, 0, 999, 4],
 [999, 999, 999, 999, 999, 0, 3],
 [999, 999, 999, 999, 999, 999, 0]]

Definimos la función Precios que servirá para calcular una matriz con los diferentes precios que exiten para de un nodo al siguiente.



In [3]:
def Precios(tarifas):

  #Total de Nodos
  n = len(tarifas[0])
  
  #Inicialización las variables que vamos a devolver en la función
  precios = [ [9999]*n for i in [9999]*n] 
  ruta = [ [""]*n for i in [""]*n]
  
  #Recorremos todos los nodos de la matriz, y de ahí hacia delante ya que no podemos volver de un nodo al anterior
  for i in range(n-1):
    for j in range(i+1, n):
      minimo = tarifas[i][j]
      ruta[i][j] = i
      
      for k in range(i, j):
        if precios[i][k] + tarifas[k][j] < minimo:
            minimo = min(minimo, precios[i][k] + tarifas[k][j] )
            ruta[i][j] = k
        precios[i][j] = minimo
        
  return precios,ruta

Precios(tarifas)

([[9999, 5, 4, 3, 8, 8, 11],
  [9999, 9999, 999, 2, 3, 8, 7],
  [9999, 9999, 9999, 1, 6, 4, 7],
  [9999, 9999, 9999, 9999, 5, 6, 9],
  [9999, 9999, 9999, 9999, 9999, 999, 4],
  [9999, 9999, 9999, 9999, 9999, 9999, 3],
  [9999, 9999, 9999, 9999, 9999, 9999, 9999]],
 [['', 0, 0, 0, 1, 2, 5],
  ['', '', 1, 1, 1, 3, 4],
  ['', '', '', 2, 3, 2, 5],
  ['', '', '', '', 3, 3, 3],
  ['', '', '', '', '', 4, 4],
  ['', '', '', '', '', '', 5],
  ['', '', '', '', '', '', '']])

In [4]:
#Calculamos la ruta a partir de la matriz obtenida en la función anterior
def calcular_ruta(ruta, desde, hasta):
  if desde == ruta[desde][hasta]:
    return desde 
  else:
    return str(calcular_ruta(ruta, desde, ruta[desde][hasta])) +  ',' + str(ruta[desde][hasta]) 

precios,ruta = Precios(tarifas)  

print("\nLa ruta es:")  
calcular_ruta(ruta, 0,6) 


La ruta es:


'0,2,5'

##Problema de Asignacion de tarea

In [5]:
#Asignación de tareas - Algoritmo de Ramificación y Poda

costes=[[11,12,18,40],
        [14,15,13,22],
        [11,17,19,23],
        [17,14,20,28]]
        

In [6]:
#Calculo del valor de una solucion parcial
def valor(S,costes):
  valor = 0
  for i in range(len(S)):
    valor += costes[S[i]][i] 
  return valor



valor((0, 1, 2, 3  ),costes)

73

In [7]:
#Coste inferior para soluciones parciales
#  (1,3,) Se asigna la tarea 1 al agente 0 y la tarea 3 al agente 1

def CI(S,costes):
  valor = 0
  #Valores establecidos
  for i in range(len(S)):
    valor += costes[i][S[i]]

  #Estimacion
  for i in range( len(S), len(costes)   ):
    valor += min( [ costes[j][i] for j in range(len(S), len(costes))  ])
  return valor

def CS(S,costes):
  valor = 0
  #Valores establecidos
  for i in range(len(S)):
    valor += costes[i][S[i]]

  #Estimacion
  for i in range( len(S), len(costes)   ):
    valor += max( [ costes[j][i] for j in range(len(S), len(costes))  ])
  return valor

CI((0,1),costes)

68

In [8]:
#Genera tantos hijos como como posibilidades haya para la siguiente elemento de la tupla
#(0,) -> (0,1), (0,2), (0,3)
def crear_hijos(nodo, N):
  hijos = []
  for i in range(N ):
    if i not in nodo:
      hijos.append({'s':nodo +(i,)    })
  return hijos

crear_hijos((0,) , 4)

[{'s': (0, 1)}, {'s': (0, 2)}, {'s': (0, 3)}]

In [9]:
def ramificacion_y_poda(COSTES):
#Construccion iterativa de soluciones(arbol). En cada etapa asignamos un agente(ramas).
#Nodos del grafo  { s:(1,2),CI:3,CS:5  }
  #print(COSTES)
  DIMENSION = len(COSTES)  
  MEJOR_SOLUCION=tuple( i for i in range(len(COSTES)) )
  CotaSup = valor(MEJOR_SOLUCION,COSTES)
  #print("Cota Superior:", CotaSup)

  NODOS=[]
  NODOS.append({'s':(), 'ci':CI((),COSTES)    } )

  iteracion = 0

  while( len(NODOS) > 0):
    iteracion +=1

    nodo_prometedor = [ min(NODOS, key=lambda x:x['ci']) ][0]['s']
    #print("Nodo prometedor:", nodo_prometedor)

    #Ramificacion
    #Se generan los hijos
    HIJOS =[ {'s':x['s'], 'ci':CI(x['s'], COSTES)   } for x in crear_hijos(nodo_prometedor, DIMENSION) ]

    #Revisamos la cota superior y nos quedamos con la mejor solucion si llegamos a una solucion final
    NODO_FINAL = [x for x in HIJOS if len(x['s']) == DIMENSION  ]
    if len(NODO_FINAL ) >0: 
      #print("\n********Soluciones:",  [x for x in HIJOS if len(x['s']) == DIMENSION  ] )
      if NODO_FINAL[0]['ci'] < CotaSup:
        CotaSup = NODO_FINAL[0]['ci']
        MEJOR_SOLUCION = NODO_FINAL
 
    #Poda
    HIJOS = [x for x in HIJOS if x['ci'] < CotaSup   ]

    #Añadimos los hijos 
    NODOS.extend(HIJOS) 

    #Eliminamos el nodo ramificado
    NODOS =  [  x for x in NODOS if x['s'] != nodo_prometedor    ]
   
  print("La solucion final es:" ,MEJOR_SOLUCION , " en " , iteracion , " iteraciones" , " para dimension: " ,DIMENSION  )
      


ramificacion_y_poda(costes)

La solucion final es: [{'s': (1, 2, 0, 3), 'ci': 64}]  en  10  iteraciones  para dimension:  4


## Algoritmo por fuerza bruta

In [10]:
import numpy as np


def contador(elemento,lista):
  cont=0
  for i in lista:
    if i==elemento:
      cont+=1
  return cont


def asignacion_tareas(costes):
  n,m=len(costes),len(costes[0])
  total=0
  tareas=[0]*n

  for i in range(n):
    minimo=costes[i][0]
    tareas[i]=1
    while contador(tareas[i],tareas)>1:
          tareas[i]+=1

    for j in range(m):
      #print(costes[i][j])
      if minimo>=costes[i][j] and (j+1 not in tareas):
        minimo=costes[i][j]
        tareas[i]=j+1
    total+=minimo

  print('Las tareas se asignan de la siguiente manera: ', tareas,'y el coste total sería: ',total)


costes=[[11,12,18,40],
        [14,15,13,22],
        [11,17,19,23],
        [17,14,20,28]]
print(asignacion_tareas(costes))

Las tareas se asignan de la siguiente manera:  [1, 3, 2, 4] y el coste total sería:  52
None


Ahora vamos a ir probando diferentes matrices aleatorias con tamaños más grandes, para ver hasta qué tamaño el algoritmo de fuerza bruta es aplicable. 

In [28]:
from numpy import random

m=np.random.randint(100,size=((8,8)))
print(m)

print(asignacion_tareas(m))
ramificacion_y_poda(m)

[[22 58 83  7 54 91 15 12]
 [33 59 12 26 64 78 82  7]
 [63 79 43 61  5 64 94  1]
 [72 16 79 61 85  7 35 70]
 [89 66 51 54 61 15 16 89]
 [55 96  3 50  7 53 26 16]
 [75 56 53 90 25 88 95 69]
 [66 49 44 60 30 54 76 20]]
Las tareas se asignan de la siguiente manera:  [4, 8, 5, 6, 7, 3, 2, 1] y el coste total sería:  167
None
La solucion final es: [{'s': (3, 0, 7, 5, 6, 2, 4, 1), 'ci': 141}]  en  420  iteraciones  para dimension:  8


In [29]:
m=np.random.randint(100,size=((100,100)))
print(m)

print(asignacion_tareas(m))
ramificacion_y_poda(m)

[[71 52 49 ...  7 15 59]
 [63 13 13 ... 75 76 97]
 [43 21 17 ... 95 83 63]
 ...
 [41 44  9 ... 51 48 32]
 [28 98  1 ... 12 14  0]
 [49 13 80 ... 70 90 93]]
Las tareas se asignan de la siguiente manera:  [28, 87, 16, 17, 58, 75, 25, 18, 41, 95, 68, 63, 47, 49, 59, 24, 30, 35, 54, 94, 48, 5, 79, 99, 100, 93, 91, 65, 88, 62, 11, 13, 12, 72, 39, 19, 70, 52, 74, 27, 43, 90, 6, 23, 73, 1, 57, 45, 26, 42, 34, 76, 77, 92, 44, 56, 60, 40, 37, 86, 71, 29, 83, 46, 69, 53, 82, 33, 20, 7, 51, 50, 36, 98, 85, 22, 15, 14, 2, 66, 21, 96, 78, 31, 3, 9, 97, 8, 4, 38, 32, 55, 81, 67, 84, 89, 64, 80, 61, 10] y el coste total sería:  265
None


KeyboardInterrupt: ignored

Para tamaño n=100, el algortimo de ramificación y poda tarda un tiempo excesivo en ejecutarse.